---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - release
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push maxiwtit-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.app
          target: 'prod'
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/maxitwit-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwit-server:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwit-server:webbuildcache,mode=max

      - name: Build and push maxitwit-api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.api
          target: 'prod'
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/maxitwit-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwit-api:apibuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maxitwit-api:apibuildcache,mode=max


      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no
          '/minitwit/deploy.sh'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
